---

# - name: "Advanced BASH Features"
#   copy:
#     src:   "etc/profile.d/{{ item }}"
#     dest:  "/etc/profile.d/{{ item }}"
#     force: yes
#     mode:  '0644'
#     directory_mode: '0755'
#   with_items:
#     - "{{ bash_advanced_features }}"

# - name: "Other /etc/profile.d Scripts"
#   template:
#     src:   "etc/profile.d/{{ item }}.j2"
#     dest:  "/etc/profile.d/{{ item }}"
#     mode:  '0644'
#     force: yes
#   with_items:
#    - 00-provisioner-vars.sh

# - name: "Custom /etc/profile.d Scripts"
#   template:
#     src:   "etc/profile.d/script.sh.j2"
#     dest:  "/etc/profile.d/{{ profile_script.name }}.sh"
#     mode:  '0644'
#     force: yes
#   with_items:
#    - "{{ bash_profile_d | default([]) }}"
#   loop_control:
#     loop_var: profile_script
