---
# # # # #  Bash  # # # # #

- name: "Require Correct Linux Distribution"
  assert:
    that: ansible_distribution == 'RedHat' and \
          ansible_distribution_major_version in [6, 7]
    msg:  "This Linux distrution is not supported by the role."
  tags: bash

- name: "Include OS Variables"
  include_vars: "vars_{{ ansible_os_family }}.yml"
  tags: bash

- name: "Remove Unwanted Scripts"
  file: path="{{ item }}" state=absent
  with_items:
   - /etc/profile.d/colorls.sh
   - /etc/profile.d/colorls.csh
  tags: bash

- name: "Global /etc/bashrc Script"
  copy: src=etc/bashrc dest=/etc/bashrc force=yes mode='0644'
  tags: bash

- name: "profile.d Configuration"
  include: profile_d.yml
  tags: bash

- name: "Advanced MOTD"
  include: motd.yml
  when: "'20-prompt.sh' in bash_advanced_features | default([])"
  tags: bash

- name: "User Configuration Files"
  become: yes
  become_user: "{{ user.username }}"
  include: user.yml
  with_items:
   - "{{ bash_users | default([]) }}"
  loop_control:
    loop_var: user
  tags: bash

# - name: "Files Permissions"
#   file:
#     path:   "{{ item }}"
#     owner:  root
#     group:  root
#     seuser: system_u
#     serole: object_r
#     setype: etc_t
#   with_items:
#     - /etc/profile.d
#     - /etc/motd.d
#     - /etc/bashrc
#   tags: bash
