---
# # # # #  Bash  # # # # #

- name: "Require Correct Linux Distribution"
  assert:
    that: ansible_distribution | lower in ['redhat', 'centos']
    msg:  "This Linux distrution is not supported by the role."
  tags: bash

- name: "Remove Unwanted Scripts"
  file: path="{{ item }}" state=absent
  with_items:
   - /etc/motd
   - /etc/profile.d/colorls.sh
   - /etc/profile.d/colorls.csh
  tags: bash

- name: "Configuration Files"
  copy:
    src:   etc/profile.d
    dest:  /etc
    force: yes
    mode:  '0644'
    directory_mode: '0755'
  tags: bash

- name: "Restricted BASH"
  file:
    src:    /bin/bash
    dest:   /bin/rbash
    state:  link
    force:  yes
    owner:  root
    group:  root
    mode:   '0777'
    seuser: system_u
    serole: object_r
    setype: shell_exec_t
  tags: bash

- name: "Login Script"
  copy: src=etc/bashrc dest=/etc/bashrc force=yes mode='0644'
  tags: bash

- name: "MOTD Directory"
  file: path=/etc/motd.d state=directory mode='0755'
  tags: bash

- name: "Message of the Day Files"
  copy:
    src:  etc/motd.d
    dest: /etc
    mode: '0755'
    force: yes
    directory_mode: '0755'
  tags: bash


- name: "Global Configuration Files"
  template:
    src:  "etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: '0644'
    force: yes
  with_items:
   - motd.d/motd
   - profile.d/00-provisioner-vars.sh
   - profile.d/99-host-overrides.sh
  tags: bash

- name: "User Configuration Files"
  become: yes
  become_user: "{{ user.username }}"
  include: user.yml
  with_items:
   - "{{ system_users | default([]) }}"
  loop_control:
    loop_var: user
  tags: bash

- name: "Files Permissions"
  file:
    path:   "{{ item }}"
    owner:  root
    group:  root
    seuser: system_u
    serole: object_r
    setype: etc_t
  with_items:
    - /etc/profile.d
    - /etc/motd.d
    - /etc/bashrc
  tags: bash
