---

- name: "Require Correct Linux Distribution"
  assert:
    that: (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_version | version_compare('6.0.0', '>=')) or
          (ansible_distribution == 'Debian'             and ansible_distribution_version | version_compare('7.0.0', '>=')) or
          (ansible_distribution == 'Ubuntu'             and ansible_distribution_version | version_compare('16.0.0', '>='))
    msg:  "This Linux distribution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
  tags: bash

- name: "Include OS Variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"
  tags: bash

- name: "OS Dependencies"
  package: name="{{ bash_os_dependencies[item.name] }}" state=present
  with_items:
   - { name: all, state: present }
   - "{{ bash_features }}"
  tags: bash

- name: "PIP Dependencies"
  pip: name="{{ bash_pip_dependencies[item.name] }}" state=present
  with_items:
   - { name: all, state: present }
   - "{{ bash_features }}"
  tags: bash

- name: "Remove Unwanted Files"
  file: path="{{ item }}" state=absent
  with_items:
   - "{{ bash_unwanted_files }}"
  tags: bash

- name: "Configure Features"
  include_tasks: "features/{{ feature.name }}.yml"
  with_items:
   - { name: all, state: present }
   - "{{ bash_features }}"
  loop_control:
    loop_var: feature
  tags: bash

- name: "User Configuration Files"
  become: yes
  become_user: "{{ user.username }}"
  include_tasks: config_user.yml
  with_items:
   - "{{ bash_users | default([]) }}"
  loop_control:
    loop_var: user
  tags: bash

# - name: "Files Permissions"
#   file:
#     path:   "{{ item }}"
#     owner:  root
#     group:  root
#     seuser: system_u
#     serole: object_r
#     setype: etc_t
#   with_items:
#     - /etc/profile.d
#     - /etc/motd.d
#     - /etc/bashrc
#   tags: bash
