---

- name: "Remove Old MOTD"
  file: path="{{ item }}" state=absent
  with_items:
   - /etc/motd

- name: "MOTD dependencies 1/2"
  package: name="{{ item }}" state=present
  with_items: "{{ bash_os_dependencies }}"

- name: "MOTD dependencies 2/2"
  pip: name="{{ item }}"
  with_items: "{{ bash_pip_dependencies }}"

- name: "MOTD Directory"
  file: path=/etc/motd.d state=directory mode='0755'

- name: "Message of the Day Scripts"
  copy:
    src:  etc/motd.d
    dest: /etc
    mode: '0755'
    force: yes
    directory_mode: '0755'

- name: "Message of the Day File"
  template:
    src:  "etc/motd.d/motd.j2"
    dest: "/etc/motd.d/motd"
    mode: '0644'
    force: yes
