---

- block:

   - name: "Aliases : Main script"
     template:
       src:   etc/profile.d/bash_aliases.sh.j2
       dest:  "{{ bash_profile_d }}/bash_aliases.sh"
       mode:  '0755'
       owner: root
       group: root

   - name: "Aliases : Directory"
     file:
       path:  "{{ bash_paths.aliases }}"
       state: directory
       mode:  '0755'

   - name: "Aliases : Copy Files"
     template:
       src:   "{{ item }}"
       dest:  "{{ bash_paths.aliases }}/{{ item | basename | regex_replace('\\.j2', '') }}"
       mode:  '0755'
       owner: root
       group: root
     with_fileglob:
      - "../../templates/etc/bash_aliases.d/*"

  when: feature.state | default('absent') == 'present'

- name: "Aliases : Main script"
  file: path="{{ bash_profile_d }}/bash_aliases.sh" state=absent
  when: feature.state | default('absent') == 'absent'

- name: "Aliases : Remove Unwanted Files in CentOS"
  block:

   - copy: remote_src=True src="{{ item }}" dest="{{ item }}-ansible-unused"
     with_items:
      - /etc/profile.d/colorls.sh
      - /etc/profile.d/colorls.csh

   - file: path="{{ item }}" state=absent
     with_items:
      - /etc/profile.d/colorls.sh
      - /etc/profile.d/colorls.csh

  when: ansible_distribution == 'CentOS'
