---

- set_fact:
    aliases_path: "{{ bash_paths.aliases }}"
  tags: bash

- name: "Aliases : Main script"
  template:
    src:   etc/profile.d/bash_aliases.sh.j2
    dest:  "{{ bash_profile_d }}/bash_aliases.sh"
    mode:  '0755'
    owner: root
    group: root
  tags: bash

- name: "Aliases : Directory"
  file:
    path:  "{{ aliases_path }}"
    state: directory
    mode:  '0755'
  tags: bash

- name: "Aliases : Copy Files"
  template:
    src:   "{{ item }}"
    dest:  "{{ aliases_path }}/{{ item | basename | regex_replace('\\.j2', '') }}"
    mode:  '0755'
    owner: root
    group: root
  with_fileglob:
   - "../../templates/etc/bash_aliases.d/*.j2"
  tags: bash

- name: "Aliases : Drop Custom Scripts Content"
  copy:
    content: "{{ item.content }}"
    dest:    "{{ aliases_path }}/{{ item.name }}"
    owner:   root
    group:   root
    mode:    '0775'
  with_items: "{{ feature['files'] | default([]) }}"
  when: item['content'] | default('') != ''
  tags: bash

- name: "Aliases : Drop Custom Scripts File"
  copy:
    src:   "{{ item.file }}"
    dest:  "{{ aliases_path }}/{{ item.name }}"
    owner: root
    group: root
    mode:  '0775'
  with_items: "{{ feature['files'] | default([]) }}"
  when: item['file'] | default('') != ''
  tags: bash

- name: "Aliases : Remove Unwanted Files in CentOS"
  block:

   - copy: remote_src=True src="{{ item }}" dest="{{ item }}-ansible-unused"
     with_items:
      - /etc/profile.d/colorls.sh
      - /etc/profile.d/colorls.csh

   - file: path="{{ item }}" state=absent
     with_items:
      - /etc/profile.d/colorls.sh
      - /etc/profile.d/colorls.csh

  when: ansible_distribution == 'CentOS'
  tags: bash
