---

- name: "MOTD : Main script"
  template:
    src:   etc/profile.d/90-motd.sh.j2
    dest:  "{{ bash_profile_d }}/90-motd.sh"
    mode:  '0755'
    owner: root
    group: root
  tags: bash

- name: "MOTD : Silence Ubuntu default MOTD scripts"
  become: yes
  ansible.builtin.find:
    paths: /etc/update-motd.d
    patterns: "*"
    file_type: file
  register: motd_scripts
  tags: bash

- name: "MOTD : Set default Ubuntu scripts to non-executable"
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ motd_scripts.files }}"
  when: "'90-custom' not in item.path"
  tags: bash

- name: "MOTD : Disable motd-news.timer"
  become: yes
  ansible.builtin.systemd:
    name: motd-news.timer
    state: stopped
    enabled: no
    masked: yes
  tags: bash

- name: "MOTD : Directory"
  ansible.builtin.file:
    path:  "{{ bash_paths.motd }}"
    state: directory
    mode:  '0755'
  tags: bash

- name: "MOTD : Copy Files"
  ansible.builtin.template:
    src:   "{{ item }}"
    dest:  "{{ bash_paths.motd }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode:  '0775'
  with_fileglob:
   - "../../templates/etc/motd.d/*.j2"
  tags: bash

- name: "MOTD : Copy text file"
  ansible.builtin.template:
    src:   "etc/motd.d/motd.j2"
    dest:  "{{ bash_paths.motd }}/motd"
    owner: root
    group: root
    mode:  '0644'
  tags: bash
