---

- name: "Prompt : Main script"
  template:
    src:   "etc/profile.d/{{ item }}.j2"
    dest:  "{{ bash_profile_d }}/{{ item }}"
    mode:  '0755'
    owner: root
    group: root
  with_items:
   - 00-colours.sh
   - 20-prompt.sh
  tags: bash
